language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  fast_finish: true

before_script:
  - sudo locale-gen fr_FR fr_FR.UTF-8
  - locale -a  
  - echo "extension = zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - printf "yes\nyes\nno\nyes\n" | pecl install pecl_http
  - composer self-update
  - mkdir test
  - cd test
  - composer init --no-interaction --stability=dev
  - composer require "photon/photon:dev-develop"
  - composer require "photon/log-syslog:dev-master"
  - cp vendor/photon/log-syslog/phpunit.xml .
  
script: phpunit -c phpunit.xml

